{% set version = "1.6.4" %}
{% set hash_type = "sha256" %}
{% set hash_value = "9a356c08bcee93289d821ecbb7cf94393d9203029fd0ebcb203edbba627df00d" %}

package:
  name: 'npstreams'
  version: '{{ version }}'

source:
  fn: 'npstreams-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/n/npstreams/npstreams-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy >=1.15

test:
  requires:
    - scipy >=1.0.0
    - pytest
  imports:
    - npstreams
  commands:
    # Pytest is better at finding tests in installed packages
    - pytest --pyargs npstreams

about:
  home: https://github.com/LaurentRDC/npstreams
  license: BSD 3-Clause
  license_family: BSD
  license_file: 'LICENSE.txt'
  summary: 'Streaming operations on NumPy arrays'
  description: |
    npstreams is an open-source Python package for streaming NumPy array operations.
    The goal is to provide tested routines that operate on streams (or generators) 
    of arrays instead of dense arrays. Streaming reduction operations (sums, averages, etc.) 
    can be implemented in constant memory, which in turns allows for easy parallelization.
  doc_url: 'https://npstreams.readthedocs.io'
  dev_url: 'https://github.com/LaurentRDC/npstreams'

extra:
  recipe-maintainers: 
    - LaurentRDC
