travis:
  secure:
    BINSTAR_TOKEN: Y61pnzLiqSugACOmrwSQPKwss0+YHKAJhm+d7iYyBqbxA9WSl8OJGksXtGNfB3zs1a5VRACqvFHBBGAJvtK2B6t5PnA4OnRK1aUBjFJBxD37ZZLDThzOFb/NvMGqVRozx1G7ooZDKn8RgksNqmxh3vAebWSCZjQV2AirNGD8LeOJ8pLU83n7m8P1Jg2m2Ud9r43MMnnfG32xAPv/tiHdk9HWgn+DEX+ZDWM1Hm/o0lbUZiTOCFz7b/RgLGszUNuxoOSaZwhzdl5zDB2jp84qG8QJjo0AXnhqsSoV4Ht7/KhiuDBF3s/Z7nDRLmMFwG7GsdOmoSa4rxKaXZzAwBOwzF88Lq/DiVosJfxdwZgzagGcNl9eSVp1yUeZUDkQphdgJC54mxmH75N6Lro9Yu3I7T+qCOaBKT2mVrDFom399u+zgt3nJQtIOXsSQ6mnks9220m6b42CzxL3R4aZLEru9h6fs+lf+i8gcLKcvNqF1y/Wp5iqYXh0HY5z1NZom0IwZ9lF+9NLBQ1kLe9D5Q1RHvjvlW95U6JS2zqdS5O1+LXFthnD07TK1ndPjKVgFKQMRaG8vt3dB2pn+0/fAyZPL5rFMhL7yYqurWgwGSxSEBbV29JOuMWOxRlqV5E4lzMYMbCHhfXjifPjebJXuwCvdGqzvHgJBfgRQGveMS30mnk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
