travis:
  secure:
    BINSTAR_TOKEN: InLOO0qT5NIit8QEp5zfjzLqHUvT2gvlcwq4GEWDm4CXZmPhzaCsIj0RjcKr7e7apm/7DSORFTtfLEMI5MHXlXrdDhN7R73HBJLINszKA1XW/9eqLJjnSfd3pWRK78v3yupxINHRSkap+EmvU2jy9/rMIIA2GfUeey9m4nSyRX1F/uuHAV+/n8KkYFElGNrReHe5VB47QAVrM89oqtHrc+MP/bBiZ9DSak6SipfEh12ggXHvGOYnO1ckTbiifNOtmlHuzR7r/Yb/dlSIfKNjkj+BsVQBM6VsftDmzQjRcJ5HQsu2occvAw/QBxDSq+2cpNp8LLEXe0xCmOA31uRnFnwLqWfTlC/RuyfbeF8LjTELJz6lQo2WtvvcoqY/i7P9LS+W9DzaddMxXpOoR1tbmNWMr6oWl+wxYYyaJqQRZ3eTBUbLvAHCb/ZGyQwZQZM4AHtawRJz4eeljFsZ5s3UbyFd7NfeQ/N78YwGpKMcmjY2cskN9XG7HOQiZPZvOlxeqQUC/eTV/3RPY3bsW9fzIwLS3O7osF3PQI/MxqPgebhsEe+mAJRrVJr/f4dLIISOOS8DjFUitNPwQtPFeNqtHKP1fUG0NP38lYXUhn4BbB3EZ+Aspdf5zuAPVum+DdCH44335WD4oNz94Qz3HYgq3jgIMmNcpAwqLmSpD/3c2us=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
